AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - spec/**/*
    - db/migrate/*.rb
    - db/schema.rb
    - lib/**/*.rake

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

