---
# Logs
log_level:                <%= ENV['LOG_LEVEL'] %>

# SSH authorized_keys file
ssh_config_file:          <%= ENV['SSH_CONFIG_FILE'] %>

# DeployIt domain name
access_domain_name:       <%= ENV['ACCESS_DOMAIN_NAME'] %>
access_url:               <%= ENV['ACCESS_URL'] %>
mail_from:                <%= ENV['MAIL_FROM'] %>

# Private Docker Registry
docker_registry:          <%= ENV['DOCKER_REGISTRY'] %>

# DeployIt directories
applications_clones_dir:  <%= ENV['APPLICATIONS_CLONES_DIR'] %>
applications_repos_dir:   <%= ENV['APPLICATIONS_REPOS_DIR'] %>
applications_datas_dir:   <%= ENV['APPLICATIONS_DATAS_DIR'] %>

# Scripts path
scripts_path:             <%= ENV['SCRIPTS_PATH'] %>
