---
# Logs
log_level:                <%= ENV['LOG_LEVEL'] %>

# DeployIt domain name
access_domain_name:       <%= ENV['ACCESS_DOMAIN_NAME'] %>
access_url:               <%= ENV['ACCESS_URL'] %>
mail_from:                <%= ENV['MAIL_FROM'] %>

# Private Docker Registry
docker_registry:          <%= ENV['DOCKER_REGISTRY'] %>

# DeployIt authentication server
authentication_server:    <%= ENV['AUTHENTICATION_SERVER'] %>
authentication_token:     <%= ENV['AUTHENTICATION_TOKEN'] %>
white_listed_ips:         <%= ENV['WHITE_LISTED_IPS'].split(',') %>

# DeployIt directories
applications_clones_dir:  <%= ENV['APPLICATIONS_CLONES_DIR'] %>
applications_repos_dir:   <%= ENV['APPLICATIONS_REPOS_DIR'] %>
applications_datas_dir:   <%= ENV['APPLICATIONS_DATAS_DIR'] %>

# Scripts path
scripts_path:             <%= ENV['SCRIPTS_PATH'] %>

# Docker
docker_connect_timeout:   <%= ENV['DOCKER_CONNECT_TIMEOUT'] || 5 %>
docker_read_timeout:      <%= ENV['DOCKER_READ_TIMEOUT'] || 90 %>
docker_write_timeout:     <%= ENV['DOCKER_WRITE_TIMEOUT'] || 30 %>

# Sidekiq
redis_host: <%= ENV['REDIS_HOST'] %>
redis_port: <%= ENV['REDIS_PORT'] %>
redis_db:   <%= ENV['REDIS_DB'] %>

# Monitoring
mail_on_application_error: <%= ENV['MAIL_ON_APPLICATION_ERROR'] %>
